version: 2.1
jobs:
  build:
    docker:
      - image: i386/ubuntu:eoan
    steps:
      - run:
          name: Accept EULAs
          command: |
            echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
      - run:
          name: Install base dependencies
          command: >
            apt-get update && apt-get install -y -q
            autoconf
            bison
            cmake
            flex
            gettext
            git-core
            intltool
            libglib2.0-dev
            libtool
            mingw-w64
            nsis
            pkg-config
            protobuf-compiler
            python
            stow
            sudo
            texinfo
            unzip
            wget
            wine-stable
            yasm
      - run:
          name: Configure Mingw for POSIX threads
          command: update-alternatives --set i686-w64-mingw32-gcc /usr/bin/i686-w64-mingw32-gcc-posix
      - run:
          name: Configure Mingw for POSIX threads
          command: update-alternatives --set i686-w64-mingw32-g++ /usr/bin/i686-w64-mingw32-g++-posix
      - checkout:
          path: /src
      - run:
          name: Create target directory
          command: mkdir -p /target/stow
      - run:
          name: Build dependencies
          command: make
          working_directory: /src/windows

workflows:
  version: 2
  all:
    jobs:
      - build

