version: 2.1
jobs:
  build:
    docker:
      - image: i386/ubuntu:eoan
    steps:
      - run:
          name: Accept EULAs
          command: |
            echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
      - run:
          name: Install base dependencies
          command: >
            apt-get update && apt-get install -y -q
            autoconf
            bison
            cmake
            flex
            gettext
            git-core
            intltool
            libglib2.0-dev
            libtool
            mingw-w64
            nsis
            pkg-config
            protobuf-compiler
            python
            stow
            sudo
            texinfo
            unzip
            wget
            wine-stable
            yasm
      - run:
          name: Configure Mingw for POSIX threads
          command: update-alternatives --set i686-w64-mingw32-gcc /usr/bin/i686-w64-mingw32-gcc-posix
      - run:
          name: Configure Mingw for POSIX threads
          command: update-alternatives --set i686-w64-mingw32-g++ /usr/bin/i686-w64-mingw32-g++-posix
      - checkout:
          path: /src
      - run:
          name: Create target directory
          command: mkdir -p /target/stow
      - run:
          name: Build dependencies
          command: make
          working_directory: /src/windows
  build_docker:
    docker:
      - image: ubuntu:bionic
    steps:
      - setup_remote_docker:
          version: 18.06.0-ce
      - checkout
      - run:
          name: Install docker client
          command: |
            set -x
            VER="18.06.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build mingw docker image
          command: docker build -t gcr.io/clementine-data/mingw-w64:$CIRCLE_BUILD_NUM -f windows.Dockerfile .

workflows:
  version: 2
  all:
    jobs:
      - build
      - build_docker

